spring:
  datasource:
    driver-class-name: org.h2.Driver
    data-username: account
    data-password: account
    url: jdbc:h2:mem:accountdb
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  application:
    name: ms1-account-service

server:
  port: ${PORT:62511}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:62500}/eureka/