spring:
  datasource:
    driver-class-name: org.h2.Driver
    data-username: account
    data-password: account
    url: jdbc:h2:mem:accountdb;DB_CLOSE_ON_EXIT=FALSE
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  application:
    name: ms1-account-service
  zipkin:
    base-url: http://localhost:62503/
  sleuth:
    sampler:
      probability: 1

server:
  port: ${PORT:62511}

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
      base-path: /

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:62500}/eureka/