server:
  port: ${PORT:62512}
spring:
  application:
      name: ms2-shipping-service
  datasource:
    driver-class-name: org.h2.Driver
    data-username: shipping
    data-password: shipping
    url: jdbc:h2:mem:shippingdb
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
cloud:
  stream:
    kafka:
      binder:
        brokers: localhost:9092
      bindings:
        inventoryAmountSuccessIn:
          destination: shipping-topic
          group: inventory-availability-check
          contentType: application/json
        inventoryAmountCheckOut:
          destination: shipping-topic
          group: inventory-availability-check
          contentType: application/json
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:62500}/eureka/